apiVersion: apps/v1
kind: Deployment
metadata:
  name: tf-serving-kitchen-model
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tf-serving-kitchen-model
  template:
    metadata:
      labels:
        app: tf-serving-kitchen-model
    spec:
      containers:
      - name: tf-serving-kitchen-model
        image: kitchen-model:v1
        resources:
          limits:
            memory: "512Mi"
            cpu: "0.5"
        ports:
        - containerPort: 8500